

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
members = ["prob01", "prob02", "prob03", "prob04", "prob05", "prob06", "prob07", "prob08", "prob09", "prob10"]
resolver = "2"
